stages:
  - build

.build:
  image: $CONTAINER_REGISTRY/builder/android
  stage: build
  before_script:
    # We store this binary file in a variable as hex with this command: `xxd -p android-app.jks`
    # Then we convert the hex back to a binary file
    - "export VERSION_CODE=$CI_PIPELINE_IID && echo $VERSION_CODE"
    - "export VERSION_SHA=`echo ${CI_COMMIT_SHA:0:8}` && echo $VERSION_SHA"
    - flutter build appbundle
  artifacts:
    paths:
      - build/app/outputs

build:debug:
  extends: .build
  script:
    - bundle exec fastlane buildDebug