default_platform(:android)

platform :android do

  desc "Builds the debug code"
  lane :buildDebug do
    gradle(
      tasks: ["assembleDebug"],
      project_dir: './android/',
    )
  end

  desc "Builds the release code"
  lane :buildRelease do
    gradle(task: "assembleRelease", project_dir: './android/')
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test", project_dir: './android')
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal', apk: 'android/app/build/outputs/apk/release/app-release.apk')
  end

  desc "Promote Internal to Alpha"
  lane :promote_internal_to_alpha do
    upload_to_play_store(track: 'internal', skip_upload_changelogs: true, track_promote_to: 'alpha')
  end

  desc "Promote Alpha to Beta"
  lane :promote_alpha_to_beta do
    upload_to_play_store(track: 'alpha', skip_upload_changelogs: true, track_promote_to: 'beta')
  end

  desc "Promote Beta to Production"
  lane :promote_beta_to_production do
    upload_to_play_store(track: 'beta', skip_upload_changelogs: true,  track_promote_to: 'production')
  end
end

platform :ios do
  lane :build do
    build_app(scheme: "MyApp")
  end
end
